#!/usr/bin/env bash
# Render the launch film WITH voiceover (and optional BGM) when the audio files
# are present. Auto-enables audio via Remotion input props — no code edits needed.
# Falls back to a silent render (burned-in captions only) if no voiceover exists.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="${1:-out/mingjing-launch.mp4}"
HAS_VO=false
HAS_BGM=false
# per-chapter voiceover lives in public/audio/vo/ (generated by scripts/gen_tts.sh)
[ -d public/audio/vo ] && [ -n "$(ls -A public/audio/vo 2>/dev/null)" ] && HAS_VO=true
[ -f public/audio/bgm.mp3 ] && HAS_BGM=true

if [ "$HAS_VO" = false ]; then
  echo "⚠  public/audio/vo/ empty — rendering SILENT (captions are burned in)."
  echo "   Run ./scripts/gen_tts.sh first (edge-tts, no API key), then re-run this script."
else
  echo "🔊 per-chapter voiceover found ($(ls public/audio/vo | wc -l) clips) — embedding aligned narration."
fi
[ "$HAS_BGM" = true ] && echo "🎵 bgm.mp3 found — embedding low-volume background music."

PROPS=$(printf '{"hasVoiceover":%s,"hasBgm":%s}' "$HAS_VO" "$HAS_BGM")
echo "→ remotion render MingJingLaunch ${OUT}  (props=${PROPS})"
npx remotion render MingJingLaunch "${OUT}" --codec=h264 --props="${PROPS}"
echo "✓ Done: ${OUT}"
ls -lh "${OUT}"
