import React from "react";
import { AbsoluteFill, Audio, getInputProps, interpolate, staticFile, useCurrentFrame } from "remotion";
import { colors, fontMono, fontSans } from "../theme";
import { absoluteCues, CHAPTERS, chapterStartsSec, sec, TOTAL_SEC } from "../timeline";
import {
  BGM_FILE,
  BGM_VOLUME,
  HAS_BGM,
  HAS_VOICEOVER,
  VOICEOVER_VOLUME,
} from "../config";

/** Burned-in captions, bottom-center. Reads the global frame. */
export const CaptionsOverlay: React.FC = () => {
  const frame = useCurrentFrame();
  const cues = absoluteCues();
  const active = cues.find((c) => frame >= c.fromFrame && frame < c.toFrame);
  if (!active) return null;
  const local = frame - active.fromFrame;
  const o = interpolate(local, [0, 8], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  return (
    <AbsoluteFill style={{ justifyContent: "flex-end", alignItems: "center", paddingBottom: 72 }}>
      <div
        style={{
          opacity: o,
          fontFamily: fontSans,
          fontSize: 30,
          fontWeight: 500,
          color: colors.text,
          backgroundColor: "rgba(10,14,16,0.72)",
          border: `1px solid ${colors.border}`,
          borderRadius: 12,
          padding: "12px 28px",
          maxWidth: 1400,
          textAlign: "center",
          backdropFilter: "blur(6px)",
        }}
      >
        {active.text}
      </div>
    </AbsoluteFill>
  );
};

/** Thin chapter-progress bar with tick marks + current chapter label, bottom. */
export const ChapterProgressOverlay: React.FC = () => {
  const frame = useCurrentFrame();
  const nowSec = frame / sec(1);
  const pct = Math.min(1, nowSec / TOTAL_SEC);
  const starts = chapterStartsSec();
  const activeIdx = starts.reduce((acc, s, i) => (nowSec >= s ? i : acc), 0);
  const active = CHAPTERS[activeIdx];

  return (
    <AbsoluteFill style={{ justifyContent: "flex-end", pointerEvents: "none" }}>
      <div style={{ padding: "0 56px 26px", display: "flex", alignItems: "center", gap: 18 }}>
        <div style={{ fontFamily: fontMono, fontSize: 17, color: colors.mirrorBright }}>{active.index}</div>
        <div style={{ fontFamily: fontSans, fontSize: 18, color: colors.textMuted, width: 230 }}>
          {active.eyebrow} · {active.title}
        </div>
        <div style={{ flex: 1, position: "relative", height: 4, borderRadius: 2, backgroundColor: colors.border }}>
          <div
            style={{
              position: "absolute",
              left: 0,
              top: 0,
              bottom: 0,
              width: `${pct * 100}%`,
              borderRadius: 2,
              backgroundColor: colors.mirror,
            }}
          />
          {starts.map((s, i) => (
            <div
              key={i}
              style={{
                position: "absolute",
                left: `${(s / TOTAL_SEC) * 100}%`,
                top: -2,
                width: 2,
                height: 8,
                backgroundColor: i <= activeIdx ? colors.mirrorBright : colors.borderSoft,
              }}
            />
          ))}
        </div>
        <div style={{ fontFamily: fontMono, fontSize: 16, color: colors.textFaint }}>
          {fmt(nowSec)} / {fmt(TOTAL_SEC)}
        </div>
      </div>
    </AbsoluteFill>
  );
};

const fmt = (s: number) => {
  const m = Math.floor(s / 60);
  const r = Math.floor(s % 60);
  return `${m}:${String(r).padStart(2, "0")}`;
};

const voiceoverOn = () => {
  const props = getInputProps() as { hasVoiceover?: boolean };
  return HAS_VOICEOVER || props.hasVoiceover === true;
};

/**
 * Per-chapter voiceover — rendered INSIDE each <Series.Sequence>, so the
 * chapter's narration (public/audio/vo/<id>.mp3, generated by scripts/gen_tts.sh)
 * plays during that scene and naturally pauses through visual-heavy beats. This
 * is how audio stays aligned to scenes & captions without a fragile global track.
 * No-op (silent) unless enabled via config or `--props='{"hasVoiceover":true}'`.
 */
export const ChapterVoice: React.FC<{ id: string }> = ({ id }) => {
  if (!voiceoverOn()) return null;
  return <Audio src={staticFile(`audio/vo/${id}.mp3`)} volume={VOICEOVER_VOLUME} />;
};

/** Optional global background music (very quiet). No-op unless enabled. */
export const Voiceover: React.FC = () => {
  const props = getInputProps() as { hasBgm?: boolean };
  const bgm = HAS_BGM || props.hasBgm === true;
  return bgm ? <Audio src={staticFile(BGM_FILE)} volume={BGM_VOLUME} /> : null;
};
